### ISSUE TITLE
Brew install?

### ISSUE THREAD

**Issue by jennifer-lara** [gomicro/flow#29]
Could you make a brew install 🙏

**Comment by dan9186** [comment]
My understanding of it what it takes to get a package listed on brew, is more than what this project has currently.

```
Niche (or self-submitted) stuff
The software in question must:

* be maintained (i.e. the last release wasn’t ages ago, it works without patching on all Homebrew-supported OS versions and has no outstanding, unpatched security vulnerabilities)
* be known
* be stable (e.g. not declared “unstable” or “beta” by upstream)
* be used
* have a homepage
```

I haven't gone through much of anything to setup a home page, nor is it really well known/used. As much as I would love to do such a thing, it would be quite the hurdle in the current state of the repo.

----

An alternative that I propose to you for now would be to download it from the releases page where it's already been compiled etc for you.

https://github.com/gomicro/flow/releases/latest

It's notably not as convenient as a `brew install flow` would be, but it's probably the best I can offer at the moment.
